# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d00c64d4391cfa270bd91e460d16805a47af535cb72615f26936f53aba880e1f9156298093868afb0fbf0c4f0bdee199b3e0ccf6088029ba11362236c371428d

test:
  secret_key_base: a42132555cae144a1689a7e9ed1a7cc11f2b9805d0e421ccf28db56c269bb9f6da93761549d2df6d42122d1fe6e7b9bf7d5fbcc45f0da4a97223661cd27225b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
